apiVersion: batch/v1
kind: Job
metadata:
  name: crypto-price-fetcher-job
spec:
  template:
    spec:
      containers:
        - name: crypto-price-fetcher
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c", "curl -X POST http://price-aggregator-service:8081/crypto/calculate/last-hour"]
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 4
